# Generated by Django 5.1.5 on 2025-02-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pregunta_secreta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='respuesta_secreta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
